package com.schedulingcli.enums;

public enum ScreenCode {
	CHOOSE_LOCALE,
	LOG_IN,
	MAIN_VIEW,
	CREATE_RECORD,
	UPCOMING_APPOINTMENTS,
	EDIT_RECORD,
    SPECIFY_RECORD,
    REPORTS,
	DELETE_RECORD, EXIT
}
